In [1]:
import numpy as np

In [2]:
# List to np array
arr = [1,2,3]
np_arr = np.array(arr)

type(arr),type(np_arr)

(list, numpy.ndarray)

In [3]:
# Create Learge array in a range
# Semillar to python range function
arr = np.arange(0,10,1) # Start, end, step
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Zero
# 1d
print(np.zeros(4))
print('='*22)
# Multi dimentional
print(np.zeros((4,5)))

# Same for np.ones()

[ 0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [5]:
# LineSpace
np.linspace(0,11,10) # start, end , number of output

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [6]:
# Random Number
print(np.random.randint(0,100))

# for dimention 
np.random.randint(0,100,(3,3))

45


array([[80, 48, 76],
       [49, 77, 70],
       [53, 47, 80]])

In [7]:
"""
Random seed helps to create some naumber everytime you ran the code
"""

for i in range(4):
    np.random.seed(1)
    print(np.random.randint(0,100,10))
print('WA seed')
print(np.random.randint(0,100,10))

[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
WA seed
[76 71  6 25 50 20 18 84 11 28]


In [12]:
arr = np.random.randint(0,100,10)
arr

array([63, 61, 22, 57,  1,  0, 60, 81,  8, 88])

In [13]:
# Reshape
arr.reshape(2,5)

array([[63, 61, 22, 57,  1],
       [ 0, 60, 81,  8, 88]])

In [23]:
arr = np.random.randint(0,100, (4,5))
arr

array([[34, 10, 23, 15, 87],
       [25, 71, 92, 74, 62],
       [46, 32, 88, 23, 55],
       [65, 77,  3,  0, 77]])

**Selecting Value from matrix**

In [25]:
arr[1,2]

92

In [31]:
arr[1:,2:]

array([[92, 74, 62],
       [88, 23, 55],
       [ 3,  0, 77]])