In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
# creating some random data
data = np.random.randint(0,100,(10,2))
data

array([[75, 51],
       [92, 40],
       [ 7, 20],
       [ 7,  8],
       [78, 43],
       [48, 73],
       [63, 81],
       [57, 34],
       [53, 42],
       [86, 79]])

## Mean Max Scaller

Minmax normalization is a normalization strategy which linearly transforms x to y= (x-min)/(max-min), where min and max are the minimum and maximum values in X, where X is the set of observed values of x. 

It can be easily seen that when x=min, then y=0, and
When x=max, then y=1.
This means, the minimum value in X is mapped to 0 and the maximum value in X is mapped to 1. So, the entire range of values of X from min to max are mapped to the range 0 to 1.

[know more about minmax function](https://www.quora.com/What-is-the-meaning-of-min-max-normalization)


In [4]:
scaller_model = MinMaxScaler()
type(scaller_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaller_model.fit(data)

C:\Users\shaha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaller_model.transform(data)

array([[ 0.8       ,  0.5890411 ],
       [ 1.        ,  0.43835616],
       [ 0.        ,  0.16438356],
       [ 0.        ,  0.        ],
       [ 0.83529412,  0.47945205],
       [ 0.48235294,  0.89041096],
       [ 0.65882353,  1.        ],
       [ 0.58823529,  0.35616438],
       [ 0.54117647,  0.46575342],
       [ 0.92941176,  0.97260274]])

In [10]:
# Perform both fit and transfrom
scaller_model.fit_transform(data)

C:\Users\shaha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.8       ,  0.5890411 ],
       [ 1.        ,  0.43835616],
       [ 0.        ,  0.16438356],
       [ 0.        ,  0.        ],
       [ 0.83529412,  0.47945205],
       [ 0.48235294,  0.89041096],
       [ 0.65882353,  1.        ],
       [ 0.58823529,  0.35616438],
       [ 0.54117647,  0.46575342],
       [ 0.92941176,  0.97260274]])

In [14]:
# crating datafram
data = np.random.randint(0,100,(50,4))
df = pd.DataFrame(data=data, columns=['f0', 'f1', 'f2', 'label'])
df.head()

f0  f1  f2  label
0   8  44  63     53
1  72  76  32     12
2   9  86  63     83
3  21  25  89     21
4  43  23  83     46

In [15]:
# Separating Data and label
X = df[['f0','f1','f2']]
y = df['label']

### Train Test split

In [16]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 2)

# Checking the train and test shape
X_train.shape, X_test.shape

((35, 3), (15, 3))